# Generated by Django 3.2.5 on 2021-07-08 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_created_model_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='id_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='events',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
